AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer for EstateWise backend

Parameters:
  VpcId:
    Type: String
  PublicSubnetIds:
    Type: CommaDelimitedList
  ServiceSecurityGroup:
    Type: String
  TargetGroupPort:
    Type: Number
    Default: 3001

Resources:
  EstateWiseALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: estatewise-alb
      Scheme: internet-facing
      Subnets: !Ref PublicSubnetIds
      SecurityGroups:
        - !Ref ServiceSecurityGroup

  EstateWiseTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: estatewise-tg
      Port: !Ref TargetGroupPort
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPath: /health
      Matcher:
        HttpCode: '200'

  EstateWiseListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref EstateWiseALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref EstateWiseTargetGroup

Outputs:
  LoadBalancerDNS:
    Description: ALB DNS Name
    Value: !GetAtt EstateWiseALB.DNSName
  TargetGroupArn:
    Description: Target Group ARN
    Value: !Ref EstateWiseTargetGroup
