AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definition and Service for EstateWise backend

Parameters:
  ClusterName:
    Type: String
  ExecutionRoleArn:
    Type: String
  ServiceRoleArn:
    Type: String
  ContainerImage:
    Type: String
  ContainerPort:
    Type: Number
    Default: 3001

Resources:
  EstateWiseTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: estatewise-backend
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ExecutionRoleArn
      ContainerDefinitions:
        - Name: backend
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Environment:
            - Name: NODE_ENV
              Value: production
            - Name: MONGO_URI
              Value: # set via SecretsManager or use Parameter Store
                Ref: MongoUriParameter

  EstateWiseService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: estatewise-backend-service
      Cluster: !Ref ClusterName
      LaunchType: FARGATE
      TaskDefinition: !Ref EstateWiseTaskDef
      DesiredCount: 2
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Split [',', !Ref PublicSubnetIds]
          SecurityGroups:
            - !Ref ServiceSecurityGroup
      Role: !Ref ServiceRoleArn

Outputs:
  ServiceName:
    Description: ECS Service Name
    Value: !Ref EstateWiseService
