AWSTemplateFormatVersion: '2010-09-09'
Description: IAM roles and policies for ECS task execution and service

Resources:
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: estatewise-ecs-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: estatewise-ecs-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSServiceRolePolicy

Outputs:
  ExecutionRoleArn:
    Description: ECS Task Execution Role ARN
    Value: !GetAtt ECSExecutionRole.Arn
  ServiceRoleArn:
    Description: ECS Service Role ARN
    Value: !GetAtt ECSServiceRole.Arn
