# Copyright (c) 2025 Son Nguyen

name: Update Lines of Code

on:
  schedule:
    - cron: "0 0 * * 0"  # weekly on Sunday @ midnight UTC
  workflow_dispatch:     # manual trigger

jobs:
  count-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq cloc locales
          sudo locale-gen en_US.UTF-8

      - name: Fetch and Clone Repositories
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # List all owned repos (public + private), non-forks
          REPOS=$(curl -H "Authorization: token $GH_PAT" -s \
            "https://api.github.com/user/repos?per_page=100&type=all" \
            | jq -r '.[] | select(.fork==false) | .full_name')

          mkdir all-repos && cd all-repos

          for REPO in $REPOS; do
            CLONE_URL="https://x-access-token:$GH_PAT@github.com/$REPO.git"
            DEFAULT_BRANCH=$(curl -H "Authorization: token $GH_PAT" -s \
              "https://api.github.com/repos/$REPO" \
              | jq -r '.default_branch')

            echo "Cloning $REPO (branch: $DEFAULT_BRANCH)…"
            git clone --depth 1 --branch "$DEFAULT_BRANCH" \
              "$CLONE_URL" "$(basename $REPO)"
          done

      - name: Calculate Lines of Code
        run: |
          echo "Running cloc…"
          cloc all-repos --exclude-ext=json,html,css,svg,md,py,ps1,scss --json \
            > cloc-output.json

      - name: Print Stats
        run: |
          TOTAL=$(jq '.SUM.code // 0' cloc-output.json)
          JS=$(jq '.JavaScript.code // 0' cloc-output.json)
          TS=$(jq '.TypeScript.code // 0' cloc-output.json)
          JSX=$(jq '.JSX.code // 0' cloc-output.json)
          CSHARP=$(jq '."C#".code // 0' cloc-output.json)
          VUE=$(jq '."Vuejs Component".code // 0' cloc-output.json)
          PHP=$(jq '.PHP.code // 0' cloc-output.json)
          OTHER=$(( TOTAL - JS - TS - JSX - CSHARP - VUE - PHP ))

          format() { export LC_ALL="en_US.UTF-8"; printf "%'d\n" "$1"; }

          echo "====== Lines of Code Summary ======"
          echo "JavaScript : $(format $JS)"
          echo "TypeScript : $(format $TS)"
          echo "JSX        : $(format $JSX)"
          echo "Vue.js     : $(format $VUE)"
          echo "PHP        : $(format $PHP)"
          echo "C#         : $(format $CSHARP)"
          echo "Other      : $(format $OTHER)"
          echo "-----------------------------------"
          echo "Total Lines: $(format $TOTAL)"
