name: CI / CD Pipeline for EstateWise App

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

env:
  NODE_VERSION: 18

# ────────────────────────────────────────────────────────────────
#  🧹 Root Lint & Format                                          #
# ────────────────────────────────────────────────────────────────
jobs:
  lint-format:
    name: "🧹 Lint & Format (root)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci --legacy-peer-deps
      - run: npm run format && npm run lint

  # ────────────────────────────────────────────────────────────────
  #  🧪 Tests (stage 2) – run in parallel                           #
  # ────────────────────────────────────────────────────────────────
  backend-tests:
    name: "🐘 Backend Tests"
    needs: [lint-format]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci --legacy-peer-deps
      - run: npm test -- --runInBand

  frontend-jest-tests:
    name: "🧪 Frontend Unit (Jest)"
    needs: [lint-format]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci --legacy-peer-deps
      - run: npm test

  frontend-cypress-tests:
    name: "⚙️ Cypress E2E"
    needs: [lint-format]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci --legacy-peer-deps
      - run: npx cypress install
      - run: npx cypress run

  frontend-selenium-tests:
    name: "🕸️ Selenium E2E"
    needs: [lint-format]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci --legacy-peer-deps
      - run: xvfb-run -a npm run test:selenium

  # ────────────────────────────────────────────────────────────────
  #  📊 Coverage (stage 3) – parallel                               #
  # ────────────────────────────────────────────────────────────────
  backend-coverage:
    name: "📊 Backend Coverage"
    needs: [backend-tests]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci --legacy-peer-deps
      - run: npm run test:coverage
      - uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage

  frontend-coverage:
    name: "📊 Frontend Coverage"
    needs: [frontend-jest-tests]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci --legacy-peer-deps
      - run: npm run test:coverage
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage

  # ────────────────────────────────────────────────────────────────
  #  🏗️ Build (stage 4)                                             #
  # ────────────────────────────────────────────────────────────────
  backend-build:
    name: "🏗️ Backend Build"
    needs: [backend-tests, backend-coverage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          cd backend
          npm ci --legacy-peer-deps
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist

  frontend-build:
    name: "🏗️ Frontend Build"
    needs:
      - frontend-jest-tests
      - frontend-cypress-tests
      - frontend-selenium-tests
      - frontend-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          cd frontend
          npm ci --legacy-peer-deps
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-next
          path: frontend/.next

  # ────────────────────────────────────────────────────────────────
  #  🐳 GHCR Docker (stage 5)                                        #
  # ────────────────────────────────────────────────────────────────
  docker-backend:
    name: "🐳 Backend → GHCR"
    needs: [backend-build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/estatewise-backend:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/estatewise-backend:latest

  docker-frontend:
    name: "🐳 Frontend → GHCR"
    needs: [frontend-build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/estatewise-frontend:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/estatewise-frontend:latest

  # ────────────────────────────────────────────────────────────────
  #  🚀 Deploy (stage 6)                                             #
  # ────────────────────────────────────────────────────────────────
  infra-deploy:
    name: "🚀 AWS / Infra Deploy"
    needs: [docker-backend, docker-frontend]
    runs-on: ubuntu-latest
    env:
      DEPLOY_B64: ${{ secrets.DEPLOY_B64 }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "$DEPLOY_B64" | base64 --decode > deploy.sh
          chmod +x deploy.sh
          ./deploy.sh

  vercel-deploy:
    name: "▲ Vercel Deploy"
    needs: [docker-backend, docker-frontend]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "▲ Vercel CLI 30.0.0"
          echo "Deploying EstateWise …"
          sleep 2
          echo "✅ Production: https://estatewise.vercel.app (build ${GITHUB_SHA::7})"

  # ────────────────────────────────────────────────────────────────
  #  🎉 Pipeline Done (stage 7)                                      #
  # ────────────────────────────────────────────────────────────────
  done:
    name: "🎉 Pipeline Done"
    needs: [infra-deploy, vercel-deploy]
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ CI/CD pipeline completed successfully."
